set_property SRC_FILE_INFO {cfile:E:/WorkSpace/project/FPGA/prj_ip/prj_ip/prj_ip.srcs/constrs_1/new/timing.xdc rfile:../../../prj_ip.srcs/constrs_1/new/timing.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_100 [get_pins clk_wiz_I/inst/mmcm_adv_inst/CLKOUT0]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_250 [get_pins clk_wiz_I/inst/mmcm_adv_inst/CLKOUT1]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_25m -source [get_pins clk_wiz_I/inst/mmcm_adv_inst/CLKOUT0] -divide_by 4 [get_pins {count2_reg[1]/Q}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_125m -source [get_pins clk_wiz_I/inst/mmcm_adv_inst/CLKOUT1] -divide_by 2 [get_pins {count1_reg[0]/Q}]
