# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/WorkSpace/project/FPGA/prj_ip/prj_ip/prj_ip.srcs/sources_1/ip/fpag_gaus_0/fpag_gaus_0.xci
# IP: The module: 'fpag_gaus_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/WorkSpace/project/FPGA/prj_ip/prj_ip/prj_ip.srcs/sources_1/ip/fpag_gaus_0/constraints/fpag_gaus.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpag_gaus_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/WorkSpace/project/FPGA/prj_ip/prj_ip/prj_ip.srcs/sources_1/ip/fpag_gaus_0/constraints/fpag_gaus_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpag_gaus_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/WorkSpace/project/FPGA/prj_ip/prj_ip/prj_ip.srcs/sources_1/ip/fpag_gaus_0/fpag_gaus_0.xci
# IP: The module: 'fpag_gaus_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/WorkSpace/project/FPGA/prj_ip/prj_ip/prj_ip.srcs/sources_1/ip/fpag_gaus_0/constraints/fpag_gaus.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpag_gaus_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/WorkSpace/project/FPGA/prj_ip/prj_ip/prj_ip.srcs/sources_1/ip/fpag_gaus_0/constraints/fpag_gaus_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpag_gaus_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
