#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.1 (64-bit)
#
# Filename    : fpag_gaus_0.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Wed Oct 09 08:57:40 +0800 2019
# SW Build 2188600 on Wed Apr  4 18:40:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: fpag_gaus_0.sh [-help]
# usage: fpag_gaus_0.sh [-lib_map_path]
# usage: fpag_gaus_0.sh [-noclean_files]
# usage: fpag_gaus_0.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'fpag_gaus_0.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm xbip_utils_v3_0_9 axi_utils_v2_0_5 xbip_pipe_v3_0_5 xbip_dsp48_wrapper_v3_0_4 xbip_dsp48_addsub_v3_0_5 xbip_dsp48_multadd_v3_0_5 xbip_bram18k_v3_0_5 mult_gen_v12_0_14 floating_point_v7_1_6)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "fpag_gaus_0.sh - Script generated by export_simulation (Vivado v2018.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog \
    "D:/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "D:/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "D:/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_utils_v3_0_9 $vhdlan_opts \
    "$ref_dir/../../../ipstatic/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_5 $vhdlan_opts \
    "$ref_dir/../../../ipstatic/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../ipstatic/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../ipstatic/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../ipstatic/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_multadd_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../ipstatic/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../ipstatic/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../ipstatic/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work floating_point_v7_1_6 $vhdlan_opts \
    "$ref_dir/../../../ipstatic/hdl/floating_point_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../ipstatic/hdl/verilog/AXIvideo2Mat.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/fifo_w8_d2_A.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/fifo_w32_d2_A.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/Filter2D.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/Filter2D_k_buf_0_xdS.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/fpag_gaus_dcmp_64wdI.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/fpag_gaus_ddiv_64vdy.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/fpag_gaus_dmul_64udo.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/fpag_gaus_faddfsuocq.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/fpag_gaus_fdiv_32pcA.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/fpag_gaus_fexp_32tde.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/fpag_gaus_fpext_3sc4.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/fpag_gaus_fptruncrcU.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/fpag_gaus_mac_mulDeQ.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/fpag_gaus_mac_mulEe0.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/fpag_gaus_mac_mulFfa.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/fpag_gaus_mac_mullbW.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/fpag_gaus_mul_41nibs.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/fpag_gaus_mul_44njbC.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/fpag_gaus_mul_45nkbM.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/fpag_gaus_mul_mulCeG.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/fpag_gaus_mul_mulmb6.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/fpag_gaus_mux_32_Bew.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/fpag_gaus_sitofp_qcK.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/fpag_gaus_uitofp_Aem.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/GaussianBlur.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/getGaussianKernel.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/getGaussianKernelncg.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/Mat2AXIvideo.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/pow_generic_float_s.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/pow_generic_floatbkb.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/pow_generic_floatcud.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/pow_generic_floatdEe.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/pow_generic_floateOg.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/pow_generic_floatfYi.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/pow_generic_floatg8j.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/pow_generic_floathbi.v" \
    "$ref_dir/../../../ipstatic/hdl/verilog/fpag_gaus.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../ipstatic/hdl/ip/fpag_gaus_ap_dcmp_0_no_dsp_64.vhd" \
    "$ref_dir/../../../ipstatic/hdl/ip/fpag_gaus_ap_ddiv_29_no_dsp_64.vhd" \
    "$ref_dir/../../../ipstatic/hdl/ip/fpag_gaus_ap_dmul_4_max_dsp_64.vhd" \
    "$ref_dir/../../../ipstatic/hdl/ip/fpag_gaus_ap_faddfsub_3_full_dsp_32.vhd" \
    "$ref_dir/../../../ipstatic/hdl/ip/fpag_gaus_ap_fdiv_14_no_dsp_32.vhd" \
    "$ref_dir/../../../ipstatic/hdl/ip/fpag_gaus_ap_fexp_7_full_dsp_32.vhd" \
    "$ref_dir/../../../ipstatic/hdl/ip/fpag_gaus_ap_fpext_0_no_dsp_32.vhd" \
    "$ref_dir/../../../ipstatic/hdl/ip/fpag_gaus_ap_fptrunc_0_no_dsp_64.vhd" \
    "$ref_dir/../../../ipstatic/hdl/ip/fpag_gaus_ap_sitofp_4_no_dsp_32.vhd" \
    "$ref_dir/../../../ipstatic/hdl/ip/fpag_gaus_ap_uitofp_4_no_dsp_32.vhd" \
    "$ref_dir/../../../../prj_ip.srcs/sources_1/ip/fpag_gaus_0/sim/fpag_gaus_0.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.fpag_gaus_0 xil_defaultlib.glbl -o fpag_gaus_0_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./fpag_gaus_0_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./fpag_gaus_0.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key fpag_gaus_0_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc fpag_gaus_0_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./fpag_gaus_0.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: fpag_gaus_0.sh [-help]\n\
Usage: fpag_gaus_0.sh [-lib_map_path]\n\
Usage: fpag_gaus_0.sh [-reset_run]\n\
Usage: fpag_gaus_0.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
