// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Filter2D (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_src_rows_V_read,
        p_src_cols_V_read,
        p_src_data_stream_V_dout,
        p_src_data_stream_V_empty_n,
        p_src_data_stream_V_read,
        p_dst_data_stream_V_din,
        p_dst_data_stream_V_full_n,
        p_dst_data_stream_V_write,
        p_kernel_val_0_V_0_read,
        p_kernel_val_0_V_1_read,
        p_kernel_val_0_V_2_read,
        p_kernel_val_1_V_0_read,
        p_kernel_val_1_V_1_read,
        p_kernel_val_1_V_2_read,
        p_kernel_val_2_V_0_read,
        p_kernel_val_2_V_1_read,
        p_kernel_val_2_V_2_read
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_pp0_stage0 = 5'd8;
parameter    ap_ST_fsm_state20 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] p_src_rows_V_read;
input  [31:0] p_src_cols_V_read;
input  [7:0] p_src_data_stream_V_dout;
input   p_src_data_stream_V_empty_n;
output   p_src_data_stream_V_read;
output  [31:0] p_dst_data_stream_V_din;
input   p_dst_data_stream_V_full_n;
output   p_dst_data_stream_V_write;
input  [15:0] p_kernel_val_0_V_0_read;
input  [15:0] p_kernel_val_0_V_1_read;
input  [15:0] p_kernel_val_0_V_2_read;
input  [15:0] p_kernel_val_1_V_0_read;
input  [15:0] p_kernel_val_1_V_1_read;
input  [15:0] p_kernel_val_1_V_2_read;
input  [15:0] p_kernel_val_2_V_0_read;
input  [15:0] p_kernel_val_2_V_1_read;
input  [15:0] p_kernel_val_2_V_2_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_V_read;
reg p_dst_data_stream_V_write;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_src_data_stream_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond388_i_reg_1789;
reg   [0:0] exitcond388_i_reg_1789_pp0_iter1_reg;
reg   [0:0] or_cond_i_i_reg_1798;
reg   [0:0] or_cond_i_i_reg_1798_pp0_iter1_reg;
reg   [0:0] icmp_reg_1734;
reg   [0:0] tmp_92_reg_1729;
reg    p_dst_data_stream_V_blk_n;
reg    ap_enable_reg_pp0_iter15;
reg   [0:0] or_cond_i_reg_1815;
reg   [0:0] or_cond_i_reg_1815_pp0_iter14_reg;
reg   [31:0] t_V_2_reg_369;
wire   [31:0] tmp_s_fu_383_p2;
wire   [31:0] tmp_86_fu_389_p2;
wire   [31:0] p_neg393_i_fu_395_p2;
wire   [31:0] tmp_87_fu_401_p2;
wire   [31:0] tmp_89_fu_413_p2;
wire  signed [23:0] OP2_V_fu_419_p1;
reg  signed [23:0] OP2_V_reg_1671;
wire  signed [23:0] OP2_V_0_1_fu_423_p1;
reg  signed [23:0] OP2_V_0_1_reg_1676;
wire  signed [23:0] OP2_V_0_2_fu_427_p1;
reg  signed [23:0] OP2_V_0_2_reg_1681;
wire  signed [23:0] OP2_V_1_fu_431_p1;
reg  signed [23:0] OP2_V_1_reg_1686;
wire  signed [23:0] OP2_V_1_1_fu_435_p1;
reg  signed [23:0] OP2_V_1_1_reg_1691;
wire  signed [23:0] OP2_V_1_2_fu_439_p1;
reg  signed [23:0] OP2_V_1_2_reg_1696;
wire  signed [23:0] OP2_V_2_fu_443_p1;
reg  signed [23:0] OP2_V_2_reg_1701;
wire  signed [23:0] OP2_V_2_1_fu_447_p1;
reg  signed [23:0] OP2_V_2_1_reg_1706;
wire  signed [23:0] OP2_V_2_2_fu_451_p1;
reg  signed [23:0] OP2_V_2_2_reg_1711;
wire   [31:0] tmp_91_fu_461_p2;
wire   [31:0] i_V_fu_472_p2;
reg   [31:0] i_V_reg_1724;
wire    ap_CS_fsm_state2;
wire   [0:0] tmp_92_fu_478_p2;
wire   [0:0] exitcond389_i_fu_467_p2;
wire   [0:0] icmp_fu_493_p2;
wire   [0:0] tmp_94_fu_499_p2;
reg   [0:0] tmp_94_reg_1739;
wire   [0:0] tmp_342_1_fu_505_p2;
reg   [0:0] tmp_342_1_reg_1743;
wire   [0:0] tmp_95_fu_511_p2;
reg   [0:0] tmp_95_reg_1747;
wire   [31:0] y_1_fu_713_p3;
reg   [31:0] y_1_reg_1754;
wire   [31:0] y_1_1_fu_729_p3;
reg   [31:0] y_1_1_reg_1759;
wire   [31:0] y_1_2_fu_745_p3;
reg   [31:0] y_1_2_reg_1764;
wire   [0:0] tmp_298_0_not_fu_753_p2;
reg   [0:0] tmp_298_0_not_reg_1769;
wire    ap_CS_fsm_state3;
wire   [1:0] tmp_119_fu_762_p1;
reg   [1:0] tmp_119_reg_1774;
wire   [1:0] tmp_120_fu_770_p1;
reg   [1:0] tmp_120_reg_1779;
wire   [1:0] tmp_121_fu_778_p1;
reg   [1:0] tmp_121_reg_1784;
wire   [0:0] exitcond388_i_fu_782_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state4_pp0_stage0_iter0;
wire    ap_block_state5_pp0_stage0_iter1;
reg    ap_predicate_op187_read_state6;
reg    ap_predicate_op198_read_state6;
reg    ap_block_state6_pp0_stage0_iter2;
wire    ap_block_state7_pp0_stage0_iter3;
wire    ap_block_state8_pp0_stage0_iter4;
wire    ap_block_state9_pp0_stage0_iter5;
wire    ap_block_state10_pp0_stage0_iter6;
wire    ap_block_state11_pp0_stage0_iter7;
wire    ap_block_state12_pp0_stage0_iter8;
wire    ap_block_state13_pp0_stage0_iter9;
wire    ap_block_state14_pp0_stage0_iter10;
wire    ap_block_state15_pp0_stage0_iter11;
wire    ap_block_state16_pp0_stage0_iter12;
wire    ap_block_state17_pp0_stage0_iter13;
wire    ap_block_state18_pp0_stage0_iter14;
reg    ap_block_state19_pp0_stage0_iter15;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] exitcond388_i_reg_1789_pp0_iter2_reg;
reg   [0:0] exitcond388_i_reg_1789_pp0_iter3_reg;
wire   [31:0] j_V_fu_787_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] or_cond_i_i_fu_834_p2;
wire   [31:0] x_fu_898_p3;
reg   [31:0] x_reg_1802;
wire   [0:0] brmerge_fu_906_p2;
reg   [0:0] brmerge_reg_1808;
reg   [0:0] brmerge_reg_1808_pp0_iter1_reg;
wire   [0:0] or_cond_i_fu_911_p2;
reg   [0:0] or_cond_i_reg_1815_pp0_iter1_reg;
reg   [0:0] or_cond_i_reg_1815_pp0_iter2_reg;
reg   [0:0] or_cond_i_reg_1815_pp0_iter3_reg;
reg   [0:0] or_cond_i_reg_1815_pp0_iter4_reg;
reg   [0:0] or_cond_i_reg_1815_pp0_iter5_reg;
reg   [0:0] or_cond_i_reg_1815_pp0_iter6_reg;
reg   [0:0] or_cond_i_reg_1815_pp0_iter7_reg;
reg   [0:0] or_cond_i_reg_1815_pp0_iter8_reg;
reg   [0:0] or_cond_i_reg_1815_pp0_iter9_reg;
reg   [0:0] or_cond_i_reg_1815_pp0_iter10_reg;
reg   [0:0] or_cond_i_reg_1815_pp0_iter11_reg;
reg   [0:0] or_cond_i_reg_1815_pp0_iter12_reg;
reg   [0:0] or_cond_i_reg_1815_pp0_iter13_reg;
reg   [9:0] k_buf_0_val_3_addr_reg_1819;
wire   [1:0] tmp_125_fu_926_p1;
reg   [1:0] tmp_125_reg_1825;
reg   [9:0] k_buf_0_val_4_addr_reg_1832;
reg   [9:0] k_buf_0_val_5_addr_reg_1838;
wire   [7:0] src_kernel_win_0_va_6_fu_1049_p3;
reg   [7:0] src_kernel_win_0_va_6_reg_1844;
reg   [7:0] src_kernel_win_0_va_6_reg_1844_pp0_iter3_reg;
wire   [7:0] src_kernel_win_0_va_7_fu_1067_p3;
reg   [7:0] src_kernel_win_0_va_7_reg_1850;
reg   [7:0] src_kernel_win_0_va_7_reg_1850_pp0_iter3_reg;
reg   [7:0] src_kernel_win_0_va_7_reg_1850_pp0_iter4_reg;
wire   [7:0] src_kernel_win_0_va_8_fu_1085_p3;
reg   [7:0] src_kernel_win_0_va_8_reg_1856;
wire  signed [23:0] r_V_3_0_1_fu_1488_p2;
reg  signed [23:0] r_V_3_0_1_reg_1862;
wire  signed [23:0] r_V_3_0_2_fu_1493_p2;
reg  signed [23:0] r_V_3_0_2_reg_1867;
wire  signed [23:0] r_V_3_1_1_fu_1498_p2;
reg  signed [23:0] r_V_3_1_1_reg_1872;
reg   [7:0] src_kernel_win_0_va_16_reg_1877;
reg   [7:0] src_kernel_win_0_va_17_reg_1882;
wire   [25:0] p_Val2_78_1_fu_1155_p2;
reg  signed [25:0] p_Val2_78_1_reg_1887;
wire  signed [25:0] grp_fu_1519_p3;
reg  signed [25:0] tmp25_reg_1892;
reg    ap_enable_reg_pp0_iter4;
wire  signed [23:0] r_V_3_2_2_fu_1534_p2;
reg  signed [23:0] r_V_3_2_2_reg_1897;
wire   [27:0] p_Val2_s_fu_1222_p2;
reg   [27:0] p_Val2_s_reg_1903;
wire   [26:0] p_Val2_78_2_2_cast_fu_1228_p2;
reg   [26:0] p_Val2_78_2_2_cast_reg_1908;
reg   [0:0] is_neg_reg_1914;
reg   [0:0] is_neg_reg_1914_pp0_iter6_reg;
reg   [0:0] is_neg_reg_1914_pp0_iter7_reg;
reg   [0:0] is_neg_reg_1914_pp0_iter8_reg;
reg   [0:0] is_neg_reg_1914_pp0_iter9_reg;
reg   [0:0] is_neg_reg_1914_pp0_iter10_reg;
reg   [0:0] is_neg_reg_1914_pp0_iter11_reg;
reg   [0:0] is_neg_reg_1914_pp0_iter12_reg;
reg   [0:0] is_neg_reg_1914_pp0_iter13_reg;
reg   [0:0] is_neg_reg_1914_pp0_iter14_reg;
wire   [0:0] tmp_i_i_fu_1242_p2;
reg   [0:0] tmp_i_i_reg_1920;
reg   [0:0] tmp_i_i_reg_1920_pp0_iter7_reg;
reg   [0:0] tmp_i_i_reg_1920_pp0_iter8_reg;
reg   [0:0] tmp_i_i_reg_1920_pp0_iter9_reg;
reg   [0:0] tmp_i_i_reg_1920_pp0_iter10_reg;
reg   [0:0] tmp_i_i_reg_1920_pp0_iter11_reg;
reg   [0:0] tmp_i_i_reg_1920_pp0_iter12_reg;
reg   [0:0] tmp_i_i_reg_1920_pp0_iter13_reg;
reg   [0:0] tmp_i_i_reg_1920_pp0_iter14_reg;
wire   [26:0] p_Val2_68_fu_1252_p3;
reg   [26:0] p_Val2_68_reg_1925;
reg   [26:0] p_Val2_68_reg_1925_pp0_iter7_reg;
wire   [27:0] p_Val2_i_i_cast_fu_1258_p1;
reg   [27:0] p_Val2_i_i_cast_reg_1930;
reg   [27:0] p_Val2_i_i_cast_reg_1930_pp0_iter7_reg;
reg   [31:0] num_zeros_fu_1280_p3;
reg   [31:0] num_zeros_reg_1936;
wire   [31:0] msb_idx_fu_1288_p2;
reg   [31:0] msb_idx_reg_1941;
reg   [31:0] msb_idx_reg_1941_pp0_iter8_reg;
reg   [31:0] msb_idx_reg_1941_pp0_iter9_reg;
reg   [31:0] msb_idx_reg_1941_pp0_iter10_reg;
reg   [31:0] msb_idx_reg_1941_pp0_iter11_reg;
reg   [31:0] msb_idx_reg_1941_pp0_iter12_reg;
reg   [31:0] msb_idx_reg_1941_pp0_iter13_reg;
reg   [31:0] msb_idx_reg_1941_pp0_iter14_reg;
wire   [30:0] msb_idx_1_fu_1305_p3;
reg   [30:0] msb_idx_1_reg_1946;
wire   [0:0] icmp2_fu_1323_p2;
reg   [0:0] icmp2_reg_1951;
wire   [0:0] tmp_133_fu_1333_p2;
reg   [0:0] tmp_133_reg_1956;
wire   [4:0] tmp_134_fu_1339_p2;
reg   [4:0] tmp_134_reg_1962;
wire   [4:0] tmp_136_fu_1345_p2;
reg   [4:0] tmp_136_reg_1967;
wire   [31:0] tmp32_V_3_fu_1415_p3;
reg   [31:0] tmp32_V_3_reg_1972;
wire   [31:0] tmp32_V_6_fu_1422_p1;
reg   [31:0] tmp32_V_6_reg_1977;
wire   [0:0] tmp_139_i_i_fu_1436_p2;
reg   [0:0] tmp_139_i_i_reg_1982;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter3;
reg    ap_condition_pp0_exit_iter2_state6;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
wire   [9:0] k_buf_0_val_3_address0;
reg    k_buf_0_val_3_ce0;
wire   [7:0] k_buf_0_val_3_q0;
reg    k_buf_0_val_3_ce1;
reg    k_buf_0_val_3_we1;
wire   [9:0] k_buf_0_val_4_address0;
reg    k_buf_0_val_4_ce0;
wire   [7:0] k_buf_0_val_4_q0;
reg    k_buf_0_val_4_ce1;
reg    k_buf_0_val_4_we1;
reg   [7:0] k_buf_0_val_4_d1;
wire   [9:0] k_buf_0_val_5_address0;
reg    k_buf_0_val_5_ce0;
wire   [7:0] k_buf_0_val_5_q0;
reg    k_buf_0_val_5_ce1;
reg    k_buf_0_val_5_we1;
reg   [7:0] k_buf_0_val_5_d1;
reg   [31:0] t_V_reg_358;
wire    ap_CS_fsm_state20;
wire   [63:0] tmp_105_fu_920_p1;
reg    ap_block_pp0_stage0_01001;
reg   [7:0] src_kernel_win_0_va_fu_172;
reg   [7:0] src_kernel_win_0_va_1_fu_176;
reg   [7:0] src_kernel_win_0_va_2_fu_180;
reg   [7:0] src_kernel_win_0_va_3_fu_184;
reg   [7:0] src_kernel_win_0_va_4_fu_188;
reg   [7:0] src_kernel_win_0_va_5_fu_192;
reg   [7:0] right_border_buf_0_s_fu_196;
wire   [7:0] col_buf_0_val_0_0_fu_959_p3;
reg   [7:0] right_border_buf_0_1_fu_200;
reg   [7:0] right_border_buf_0_2_fu_204;
reg   [7:0] right_border_buf_0_3_fu_208;
wire   [7:0] col_buf_0_val_1_0_fu_977_p3;
reg   [7:0] right_border_buf_0_4_fu_212;
reg   [7:0] right_border_buf_0_5_fu_216;
wire   [7:0] col_buf_0_val_2_0_fu_995_p3;
wire   [31:0] tmp_99_fu_407_p2;
wire   [31:0] tmp_101_fu_455_p2;
wire   [30:0] tmp_102_fu_483_p4;
wire   [31:0] tmp_96_fu_516_p2;
wire   [0:0] tmp_104_fu_522_p3;
wire   [0:0] tmp_97_fu_536_p2;
wire   [0:0] rev_fu_530_p2;
wire   [0:0] tmp_114_fu_547_p3;
wire   [31:0] p_assign_7_fu_555_p2;
wire   [31:0] p_p2_i425_i_fu_561_p3;
wire   [31:0] p_assign_6_1_fu_579_p2;
wire   [0:0] tmp_115_fu_585_p3;
wire   [0:0] tmp_368_1_fu_599_p2;
wire   [0:0] rev1_fu_593_p2;
wire   [0:0] tmp_116_fu_610_p3;
wire   [31:0] p_assign_7_1_fu_618_p2;
wire   [31:0] p_p2_i425_i_1_fu_624_p3;
wire   [31:0] p_assign_6_2_fu_642_p2;
wire   [0:0] tmp_117_fu_648_p3;
wire   [0:0] tmp_368_2_fu_662_p2;
wire   [0:0] rev2_fu_656_p2;
wire   [0:0] tmp_118_fu_673_p3;
wire   [31:0] p_assign_7_2_fu_681_p2;
wire   [31:0] p_p2_i425_i_2_fu_687_p3;
wire   [0:0] tmp_98_fu_569_p2;
wire   [31:0] p_assign_8_fu_574_p2;
wire   [0:0] or_cond_i424_i_fu_541_p2;
wire   [31:0] p_p2_i425_i_p_assign_8_fu_705_p3;
wire   [0:0] tmp_378_1_fu_632_p2;
wire   [31:0] p_assign_8_1_fu_637_p2;
wire   [0:0] or_cond_i424_i_1_fu_604_p2;
wire   [31:0] p_p2_i425_i_1_p_assig_fu_721_p3;
wire   [0:0] tmp_378_2_fu_695_p2;
wire   [31:0] p_assign_8_2_fu_700_p2;
wire   [0:0] or_cond_i424_i_2_fu_667_p2;
wire   [31:0] p_p2_i425_i_2_p_assig_fu_737_p3;
wire   [31:0] row_assign_8_fu_758_p2;
wire   [31:0] row_assign_8_1_fu_766_p2;
wire   [31:0] row_assign_8_2_fu_774_p2;
wire   [30:0] tmp_122_fu_793_p4;
wire   [31:0] ImagLoc_x_fu_809_p2;
wire   [0:0] tmp_123_fu_815_p3;
wire   [0:0] tmp_100_fu_829_p2;
wire   [0:0] rev3_fu_823_p2;
wire   [0:0] tmp_124_fu_840_p3;
wire   [31:0] p_assign_1_fu_848_p2;
wire   [31:0] p_p2_i_i_fu_854_p3;
wire   [31:0] p_assign_2_fu_867_p2;
wire   [0:0] tmp_103_not_fu_880_p2;
wire   [0:0] tmp_103_fu_862_p2;
wire   [0:0] sel_tmp7_fu_886_p2;
wire   [0:0] sel_tmp8_fu_892_p2;
wire   [31:0] p_assign_3_fu_872_p3;
wire   [0:0] icmp1_fu_803_p2;
wire   [31:0] col_assign_1_fu_916_p2;
wire   [7:0] tmp_106_fu_948_p5;
wire   [7:0] tmp_107_fu_966_p5;
wire   [7:0] tmp_108_fu_984_p5;
wire   [7:0] tmp_109_fu_1038_p5;
wire   [7:0] tmp_110_fu_1056_p5;
wire   [7:0] tmp_111_fu_1074_p5;
wire  signed [24:0] grp_fu_1503_p3;
wire  signed [24:0] grp_fu_1511_p3;
wire  signed [25:0] tmp21_cast_fu_1152_p1;
wire  signed [25:0] p_Val2_78_0_1_cast_fu_1142_p1;
wire  signed [24:0] grp_fu_1526_p3;
wire  signed [26:0] tmp25_cast_fu_1204_p1;
wire  signed [26:0] grp_fu_1539_p3;
(* use_dsp48 = "no" *) wire  signed [26:0] p_Val2_78_2_1_fu_1207_p2;
wire  signed [27:0] p_Val2_78_2_1_cast_fu_1212_p1;
wire  signed [27:0] tmp_386_2_2_fu_1216_p1;
wire  signed [26:0] tmp_112_fu_1219_p1;
wire   [26:0] tmp_i_i_cast_fu_1247_p2;
reg   [27:0] p_Result_17_fu_1262_p4;
wire   [31:0] p_Result_18_fu_1272_p3;
wire   [0:0] tmp_130_fu_1297_p3;
wire   [30:0] tmp_129_fu_1293_p1;
wire   [25:0] tmp_131_fu_1313_p4;
wire   [4:0] tmp_132_fu_1329_p1;
wire   [30:0] tmp_137_i_i_fu_1354_p2;
wire   [31:0] tmp32_V_fu_1351_p1;
wire   [31:0] tmp_137_i_i_cast_fu_1359_p1;
reg   [27:0] tmp_135_fu_1369_p4;
wire   [4:0] tmp_138_fu_1384_p3;
wire   [27:0] tmp_137_fu_1378_p3;
wire   [27:0] tmp_139_fu_1389_p1;
wire   [27:0] tmp_140_fu_1393_p2;
wire   [1:0] tmp_141_fu_1399_p1;
wire   [27:0] p_Result_s_fu_1403_p3;
wire   [31:0] tmp32_V_1_fu_1363_p2;
wire   [31:0] tmp32_V_2_fu_1411_p1;
wire   [31:0] grp_fu_380_p1;
wire   [7:0] p_Result_i_i_fu_1426_p4;
wire   [7:0] tmp27_cast_cast_fu_1445_p3;
wire   [7:0] tmp_143_fu_1442_p1;
wire   [7:0] p_Repl2_10_trunc_i_fu_1452_p2;
wire   [8:0] tmp_70_i_i_fu_1458_p3;
wire   [31:0] p_Result_19_fu_1465_p5;
wire   [31:0] f_fu_1476_p1;
wire  signed [15:0] r_V_3_0_1_fu_1488_p0;
wire   [7:0] r_V_3_0_1_fu_1488_p1;
wire  signed [15:0] r_V_3_0_2_fu_1493_p0;
wire   [7:0] r_V_3_0_2_fu_1493_p1;
wire  signed [15:0] r_V_3_1_1_fu_1498_p0;
wire   [7:0] r_V_3_1_1_fu_1498_p1;
wire  signed [15:0] grp_fu_1503_p0;
wire   [7:0] grp_fu_1503_p1;
wire  signed [15:0] grp_fu_1511_p0;
wire   [7:0] grp_fu_1511_p1;
wire  signed [15:0] grp_fu_1519_p0;
wire   [7:0] grp_fu_1519_p1;
wire  signed [15:0] grp_fu_1526_p0;
wire   [7:0] grp_fu_1526_p1;
wire  signed [15:0] r_V_3_2_2_fu_1534_p0;
wire   [7:0] r_V_3_2_2_fu_1534_p1;
wire  signed [15:0] grp_fu_1539_p0;
wire   [7:0] grp_fu_1539_p1;
reg    grp_fu_380_ce;
reg   [4:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [23:0] grp_fu_1503_p10;
wire   [23:0] grp_fu_1511_p10;
wire   [23:0] grp_fu_1519_p10;
wire   [23:0] grp_fu_1526_p10;
wire   [23:0] grp_fu_1539_p10;
wire   [23:0] r_V_3_0_1_fu_1488_p10;
wire   [23:0] r_V_3_0_2_fu_1493_p10;
wire   [23:0] r_V_3_1_1_fu_1498_p10;
wire   [23:0] r_V_3_2_2_fu_1534_p10;
reg    ap_condition_538;
reg    ap_condition_532;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
end

Filter2D_k_buf_0_xdS #(
    .DataWidth( 8 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
k_buf_0_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_3_address0),
    .ce0(k_buf_0_val_3_ce0),
    .q0(k_buf_0_val_3_q0),
    .address1(k_buf_0_val_3_addr_reg_1819),
    .ce1(k_buf_0_val_3_ce1),
    .we1(k_buf_0_val_3_we1),
    .d1(p_src_data_stream_V_dout)
);

Filter2D_k_buf_0_xdS #(
    .DataWidth( 8 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
k_buf_0_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_4_address0),
    .ce0(k_buf_0_val_4_ce0),
    .q0(k_buf_0_val_4_q0),
    .address1(k_buf_0_val_4_addr_reg_1832),
    .ce1(k_buf_0_val_4_ce1),
    .we1(k_buf_0_val_4_we1),
    .d1(k_buf_0_val_4_d1)
);

Filter2D_k_buf_0_xdS #(
    .DataWidth( 8 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
k_buf_0_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_5_address0),
    .ce0(k_buf_0_val_5_ce0),
    .q0(k_buf_0_val_5_q0),
    .address1(k_buf_0_val_5_addr_reg_1838),
    .ce1(k_buf_0_val_5_ce1),
    .we1(k_buf_0_val_5_we1),
    .d1(k_buf_0_val_5_d1)
);

fpag_gaus_uitofp_Aem #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fpag_gaus_uitofp_Aem_U52(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp32_V_3_reg_1972),
    .ce(grp_fu_380_ce),
    .dout(grp_fu_380_p1)
);

fpag_gaus_mux_32_Bew #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
fpag_gaus_mux_32_Bew_U53(
    .din0(right_border_buf_0_s_fu_196),
    .din1(right_border_buf_0_1_fu_200),
    .din2(8'd0),
    .din3(tmp_125_reg_1825),
    .dout(tmp_106_fu_948_p5)
);

fpag_gaus_mux_32_Bew #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
fpag_gaus_mux_32_Bew_U54(
    .din0(right_border_buf_0_3_fu_208),
    .din1(right_border_buf_0_4_fu_212),
    .din2(8'd0),
    .din3(tmp_125_reg_1825),
    .dout(tmp_107_fu_966_p5)
);

fpag_gaus_mux_32_Bew #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
fpag_gaus_mux_32_Bew_U55(
    .din0(right_border_buf_0_5_fu_216),
    .din1(right_border_buf_0_2_fu_204),
    .din2(8'd0),
    .din3(tmp_125_reg_1825),
    .dout(tmp_108_fu_984_p5)
);

fpag_gaus_mux_32_Bew #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
fpag_gaus_mux_32_Bew_U56(
    .din0(col_buf_0_val_0_0_fu_959_p3),
    .din1(col_buf_0_val_1_0_fu_977_p3),
    .din2(col_buf_0_val_2_0_fu_995_p3),
    .din3(tmp_119_reg_1774),
    .dout(tmp_109_fu_1038_p5)
);

fpag_gaus_mux_32_Bew #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
fpag_gaus_mux_32_Bew_U57(
    .din0(col_buf_0_val_0_0_fu_959_p3),
    .din1(col_buf_0_val_1_0_fu_977_p3),
    .din2(col_buf_0_val_2_0_fu_995_p3),
    .din3(tmp_120_reg_1779),
    .dout(tmp_110_fu_1056_p5)
);

fpag_gaus_mux_32_Bew #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
fpag_gaus_mux_32_Bew_U58(
    .din0(col_buf_0_val_0_0_fu_959_p3),
    .din1(col_buf_0_val_1_0_fu_977_p3),
    .din2(col_buf_0_val_2_0_fu_995_p3),
    .din3(tmp_121_reg_1784),
    .dout(tmp_111_fu_1074_p5)
);

fpag_gaus_mul_mulCeG #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
fpag_gaus_mul_mulCeG_U59(
    .din0(r_V_3_0_1_fu_1488_p0),
    .din1(r_V_3_0_1_fu_1488_p1),
    .dout(r_V_3_0_1_fu_1488_p2)
);

fpag_gaus_mul_mulCeG #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
fpag_gaus_mul_mulCeG_U60(
    .din0(r_V_3_0_2_fu_1493_p0),
    .din1(r_V_3_0_2_fu_1493_p1),
    .dout(r_V_3_0_2_fu_1493_p2)
);

fpag_gaus_mul_mulCeG #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
fpag_gaus_mul_mulCeG_U61(
    .din0(r_V_3_1_1_fu_1498_p0),
    .din1(r_V_3_1_1_fu_1498_p1),
    .dout(r_V_3_1_1_fu_1498_p2)
);

fpag_gaus_mac_mulDeQ #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
fpag_gaus_mac_mulDeQ_U62(
    .din0(grp_fu_1503_p0),
    .din1(grp_fu_1503_p1),
    .din2(r_V_3_0_1_reg_1862),
    .dout(grp_fu_1503_p3)
);

fpag_gaus_mac_mulDeQ #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
fpag_gaus_mac_mulDeQ_U63(
    .din0(grp_fu_1511_p0),
    .din1(grp_fu_1511_p1),
    .din2(r_V_3_0_2_reg_1867),
    .dout(grp_fu_1511_p3)
);

fpag_gaus_mac_mulEe0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 25 ),
    .dout_WIDTH( 26 ))
fpag_gaus_mac_mulEe0_U64(
    .din0(grp_fu_1519_p0),
    .din1(grp_fu_1519_p1),
    .din2(grp_fu_1526_p3),
    .dout(grp_fu_1519_p3)
);

fpag_gaus_mac_mulDeQ #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
fpag_gaus_mac_mulDeQ_U65(
    .din0(grp_fu_1526_p0),
    .din1(grp_fu_1526_p1),
    .din2(r_V_3_1_1_reg_1872),
    .dout(grp_fu_1526_p3)
);

fpag_gaus_mul_mulCeG #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
fpag_gaus_mul_mulCeG_U66(
    .din0(r_V_3_2_2_fu_1534_p0),
    .din1(r_V_3_2_2_fu_1534_p1),
    .dout(r_V_3_2_2_fu_1534_p2)
);

fpag_gaus_mac_mulFfa #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 27 ))
fpag_gaus_mac_mulFfa_U67(
    .din0(grp_fu_1539_p0),
    .din1(grp_fu_1539_p1),
    .din2(p_Val2_78_1_reg_1887),
    .dout(grp_fu_1539_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((exitcond388_i_fu_782_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp0_iter15 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter2_state6)) begin
                ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter1;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond388_i_fu_782_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        t_V_2_reg_369 <= j_V_fu_787_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        t_V_2_reg_369 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        t_V_reg_358 <= i_V_reg_1724;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        t_V_reg_358 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        OP2_V_0_1_reg_1676 <= OP2_V_0_1_fu_423_p1;
        OP2_V_0_2_reg_1681 <= OP2_V_0_2_fu_427_p1;
        OP2_V_1_1_reg_1691 <= OP2_V_1_1_fu_435_p1;
        OP2_V_1_2_reg_1696 <= OP2_V_1_2_fu_439_p1;
        OP2_V_1_reg_1686 <= OP2_V_1_fu_431_p1;
        OP2_V_2_1_reg_1706 <= OP2_V_2_1_fu_447_p1;
        OP2_V_2_2_reg_1711 <= OP2_V_2_2_fu_451_p1;
        OP2_V_2_reg_1701 <= OP2_V_2_fu_443_p1;
        OP2_V_reg_1671 <= OP2_V_fu_419_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond388_i_fu_782_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        brmerge_reg_1808 <= brmerge_fu_906_p2;
        or_cond_i_i_reg_1798 <= or_cond_i_i_fu_834_p2;
        or_cond_i_reg_1815 <= or_cond_i_fu_911_p2;
        x_reg_1802 <= x_fu_898_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        brmerge_reg_1808_pp0_iter1_reg <= brmerge_reg_1808;
        exitcond388_i_reg_1789 <= exitcond388_i_fu_782_p2;
        exitcond388_i_reg_1789_pp0_iter1_reg <= exitcond388_i_reg_1789;
        or_cond_i_i_reg_1798_pp0_iter1_reg <= or_cond_i_i_reg_1798;
        or_cond_i_reg_1815_pp0_iter1_reg <= or_cond_i_reg_1815;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        exitcond388_i_reg_1789_pp0_iter2_reg <= exitcond388_i_reg_1789_pp0_iter1_reg;
        exitcond388_i_reg_1789_pp0_iter3_reg <= exitcond388_i_reg_1789_pp0_iter2_reg;
        is_neg_reg_1914_pp0_iter10_reg <= is_neg_reg_1914_pp0_iter9_reg;
        is_neg_reg_1914_pp0_iter11_reg <= is_neg_reg_1914_pp0_iter10_reg;
        is_neg_reg_1914_pp0_iter12_reg <= is_neg_reg_1914_pp0_iter11_reg;
        is_neg_reg_1914_pp0_iter13_reg <= is_neg_reg_1914_pp0_iter12_reg;
        is_neg_reg_1914_pp0_iter14_reg <= is_neg_reg_1914_pp0_iter13_reg;
        is_neg_reg_1914_pp0_iter6_reg <= is_neg_reg_1914;
        is_neg_reg_1914_pp0_iter7_reg <= is_neg_reg_1914_pp0_iter6_reg;
        is_neg_reg_1914_pp0_iter8_reg <= is_neg_reg_1914_pp0_iter7_reg;
        is_neg_reg_1914_pp0_iter9_reg <= is_neg_reg_1914_pp0_iter8_reg;
        msb_idx_reg_1941_pp0_iter10_reg <= msb_idx_reg_1941_pp0_iter9_reg;
        msb_idx_reg_1941_pp0_iter11_reg <= msb_idx_reg_1941_pp0_iter10_reg;
        msb_idx_reg_1941_pp0_iter12_reg <= msb_idx_reg_1941_pp0_iter11_reg;
        msb_idx_reg_1941_pp0_iter13_reg <= msb_idx_reg_1941_pp0_iter12_reg;
        msb_idx_reg_1941_pp0_iter14_reg <= msb_idx_reg_1941_pp0_iter13_reg;
        msb_idx_reg_1941_pp0_iter8_reg <= msb_idx_reg_1941;
        msb_idx_reg_1941_pp0_iter9_reg <= msb_idx_reg_1941_pp0_iter8_reg;
        or_cond_i_reg_1815_pp0_iter10_reg <= or_cond_i_reg_1815_pp0_iter9_reg;
        or_cond_i_reg_1815_pp0_iter11_reg <= or_cond_i_reg_1815_pp0_iter10_reg;
        or_cond_i_reg_1815_pp0_iter12_reg <= or_cond_i_reg_1815_pp0_iter11_reg;
        or_cond_i_reg_1815_pp0_iter13_reg <= or_cond_i_reg_1815_pp0_iter12_reg;
        or_cond_i_reg_1815_pp0_iter14_reg <= or_cond_i_reg_1815_pp0_iter13_reg;
        or_cond_i_reg_1815_pp0_iter2_reg <= or_cond_i_reg_1815_pp0_iter1_reg;
        or_cond_i_reg_1815_pp0_iter3_reg <= or_cond_i_reg_1815_pp0_iter2_reg;
        or_cond_i_reg_1815_pp0_iter4_reg <= or_cond_i_reg_1815_pp0_iter3_reg;
        or_cond_i_reg_1815_pp0_iter5_reg <= or_cond_i_reg_1815_pp0_iter4_reg;
        or_cond_i_reg_1815_pp0_iter6_reg <= or_cond_i_reg_1815_pp0_iter5_reg;
        or_cond_i_reg_1815_pp0_iter7_reg <= or_cond_i_reg_1815_pp0_iter6_reg;
        or_cond_i_reg_1815_pp0_iter8_reg <= or_cond_i_reg_1815_pp0_iter7_reg;
        or_cond_i_reg_1815_pp0_iter9_reg <= or_cond_i_reg_1815_pp0_iter8_reg;
        p_Val2_68_reg_1925_pp0_iter7_reg <= p_Val2_68_reg_1925;
        p_Val2_i_i_cast_reg_1930_pp0_iter7_reg[26 : 0] <= p_Val2_i_i_cast_reg_1930[26 : 0];
        src_kernel_win_0_va_6_reg_1844_pp0_iter3_reg <= src_kernel_win_0_va_6_reg_1844;
        src_kernel_win_0_va_7_reg_1850_pp0_iter3_reg <= src_kernel_win_0_va_7_reg_1850;
        src_kernel_win_0_va_7_reg_1850_pp0_iter4_reg <= src_kernel_win_0_va_7_reg_1850_pp0_iter3_reg;
        tmp_i_i_reg_1920_pp0_iter10_reg <= tmp_i_i_reg_1920_pp0_iter9_reg;
        tmp_i_i_reg_1920_pp0_iter11_reg <= tmp_i_i_reg_1920_pp0_iter10_reg;
        tmp_i_i_reg_1920_pp0_iter12_reg <= tmp_i_i_reg_1920_pp0_iter11_reg;
        tmp_i_i_reg_1920_pp0_iter13_reg <= tmp_i_i_reg_1920_pp0_iter12_reg;
        tmp_i_i_reg_1920_pp0_iter14_reg <= tmp_i_i_reg_1920_pp0_iter13_reg;
        tmp_i_i_reg_1920_pp0_iter7_reg <= tmp_i_i_reg_1920;
        tmp_i_i_reg_1920_pp0_iter8_reg <= tmp_i_i_reg_1920_pp0_iter7_reg;
        tmp_i_i_reg_1920_pp0_iter9_reg <= tmp_i_i_reg_1920_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_V_reg_1724 <= i_V_fu_472_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_1815_pp0_iter6_reg == 1'd1) & (tmp_i_i_reg_1920 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp2_reg_1951 <= icmp2_fu_1323_p2;
        msb_idx_1_reg_1946 <= msb_idx_1_fu_1305_p3;
        msb_idx_reg_1941 <= msb_idx_fu_1288_p2;
        tmp_133_reg_1956 <= tmp_133_fu_1333_p2;
        tmp_134_reg_1962 <= tmp_134_fu_1339_p2;
        tmp_136_reg_1967 <= tmp_136_fu_1345_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond389_i_fu_467_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        icmp_reg_1734 <= icmp_fu_493_p2;
        tmp_342_1_reg_1743 <= tmp_342_1_fu_505_p2;
        tmp_92_reg_1729 <= tmp_92_fu_478_p2;
        tmp_94_reg_1739 <= tmp_94_fu_499_p2;
        tmp_95_reg_1747 <= tmp_95_fu_511_p2;
        y_1_1_reg_1759 <= y_1_1_fu_729_p3;
        y_1_2_reg_1764 <= y_1_2_fu_745_p3;
        y_1_reg_1754 <= y_1_fu_713_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_1815_pp0_iter4_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        is_neg_reg_1914 <= p_Val2_s_fu_1222_p2[32'd27];
        p_Val2_78_2_2_cast_reg_1908 <= p_Val2_78_2_2_cast_fu_1228_p2;
        p_Val2_s_reg_1903 <= p_Val2_s_fu_1222_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond388_i_reg_1789 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_3_addr_reg_1819 <= tmp_105_fu_920_p1;
        k_buf_0_val_4_addr_reg_1832 <= tmp_105_fu_920_p1;
        k_buf_0_val_5_addr_reg_1838 <= tmp_105_fu_920_p1;
        tmp_125_reg_1825 <= tmp_125_fu_926_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_1815_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        num_zeros_reg_1936 <= num_zeros_fu_1280_p3;
        p_Val2_68_reg_1925 <= p_Val2_68_fu_1252_p3;
        p_Val2_i_i_cast_reg_1930[26 : 0] <= p_Val2_i_i_cast_fu_1258_p1[26 : 0];
        tmp_i_i_reg_1920 <= tmp_i_i_fu_1242_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_1815_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Val2_78_1_reg_1887 <= p_Val2_78_1_fu_1155_p2;
        r_V_3_2_2_reg_1897 <= r_V_3_2_2_fu_1534_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_1815_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        r_V_3_0_1_reg_1862 <= r_V_3_0_1_fu_1488_p2;
        r_V_3_0_2_reg_1867 <= r_V_3_0_2_fu_1493_p2;
        r_V_3_1_1_reg_1872 <= r_V_3_1_1_fu_1498_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op198_read_state6 == 1'b1))) begin
        right_border_buf_0_1_fu_200 <= right_border_buf_0_s_fu_196;
        right_border_buf_0_2_fu_204 <= right_border_buf_0_5_fu_216;
        right_border_buf_0_3_fu_208 <= col_buf_0_val_1_0_fu_977_p3;
        right_border_buf_0_4_fu_212 <= right_border_buf_0_3_fu_208;
        right_border_buf_0_5_fu_216 <= col_buf_0_val_2_0_fu_995_p3;
        right_border_buf_0_s_fu_196 <= col_buf_0_val_0_0_fu_959_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond388_i_reg_1789_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_16_reg_1877 <= src_kernel_win_0_va_2_fu_180;
        src_kernel_win_0_va_17_reg_1882 <= src_kernel_win_0_va_4_fu_188;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond388_i_reg_1789_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_1_fu_176 <= src_kernel_win_0_va_fu_172;
        src_kernel_win_0_va_3_fu_184 <= src_kernel_win_0_va_16_reg_1877;
        src_kernel_win_0_va_5_fu_192 <= src_kernel_win_0_va_17_reg_1882;
        src_kernel_win_0_va_fu_172 <= src_kernel_win_0_va_6_reg_1844_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond388_i_reg_1789_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_2_fu_180 <= src_kernel_win_0_va_7_reg_1850;
        src_kernel_win_0_va_4_fu_188 <= src_kernel_win_0_va_8_reg_1856;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond388_i_reg_1789_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_6_reg_1844 <= src_kernel_win_0_va_6_fu_1049_p3;
        src_kernel_win_0_va_7_reg_1850 <= src_kernel_win_0_va_7_fu_1067_p3;
        src_kernel_win_0_va_8_reg_1856 <= src_kernel_win_0_va_8_fu_1085_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_1815_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp25_reg_1892 <= grp_fu_1519_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_1815_pp0_iter7_reg == 1'd1) & (tmp_i_i_reg_1920_pp0_iter7_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp32_V_3_reg_1972 <= tmp32_V_3_fu_1415_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_1815_pp0_iter13_reg == 1'd1) & (tmp_i_i_reg_1920_pp0_iter13_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp32_V_6_reg_1977 <= tmp32_V_6_fu_1422_p1;
        tmp_139_i_i_reg_1982 <= tmp_139_i_i_fu_1436_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_95_reg_1747 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_119_reg_1774 <= tmp_119_fu_762_p1;
        tmp_120_reg_1779 <= tmp_120_fu_770_p1;
        tmp_121_reg_1784 <= tmp_121_fu_778_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_298_0_not_reg_1769 <= tmp_298_0_not_fu_753_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_condition_pp0_exit_iter2_state6 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter2_state6 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((exitcond389_i_fu_467_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond389_i_fu_467_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_380_ce = 1'b1;
    end else begin
        grp_fu_380_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_3_ce0 = 1'b1;
    end else begin
        k_buf_0_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_94_reg_1739 == 1'd1) & (or_cond_i_i_reg_1798_pp0_iter1_reg == 1'd1) & (icmp_reg_1734 == 1'd0) & (exitcond388_i_reg_1789_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op198_read_state6 == 1'b1)))) begin
        k_buf_0_val_3_ce1 = 1'b1;
    end else begin
        k_buf_0_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_94_reg_1739 == 1'd1) & (or_cond_i_i_reg_1798_pp0_iter1_reg == 1'd1) & (icmp_reg_1734 == 1'd0) & (exitcond388_i_reg_1789_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op198_read_state6 == 1'b1)))) begin
        k_buf_0_val_3_we1 = 1'b1;
    end else begin
        k_buf_0_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_4_ce0 = 1'b1;
    end else begin
        k_buf_0_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_342_1_reg_1743 == 1'd1) & (or_cond_i_i_reg_1798_pp0_iter1_reg == 1'd1) & (icmp_reg_1734 == 1'd0) & (exitcond388_i_reg_1789_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op198_read_state6 == 1'b1)))) begin
        k_buf_0_val_4_ce1 = 1'b1;
    end else begin
        k_buf_0_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op198_read_state6 == 1'b1)) begin
            k_buf_0_val_4_d1 = k_buf_0_val_3_q0;
        end else if ((1'b1 == ap_condition_538)) begin
            k_buf_0_val_4_d1 = p_src_data_stream_V_dout;
        end else begin
            k_buf_0_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_342_1_reg_1743 == 1'd1) & (or_cond_i_i_reg_1798_pp0_iter1_reg == 1'd1) & (icmp_reg_1734 == 1'd0) & (exitcond388_i_reg_1789_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op198_read_state6 == 1'b1)))) begin
        k_buf_0_val_4_we1 = 1'b1;
    end else begin
        k_buf_0_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_5_ce0 = 1'b1;
    end else begin
        k_buf_0_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_94_reg_1739 == 1'd1) & (or_cond_i_i_reg_1798_pp0_iter1_reg == 1'd1) & (icmp_reg_1734 == 1'd0) & (exitcond388_i_reg_1789_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op198_read_state6 == 1'b1)))) begin
        k_buf_0_val_5_ce1 = 1'b1;
    end else begin
        k_buf_0_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((ap_predicate_op198_read_state6 == 1'b1)) begin
            k_buf_0_val_5_d1 = k_buf_0_val_4_q0;
        end else if ((1'b1 == ap_condition_532)) begin
            k_buf_0_val_5_d1 = p_src_data_stream_V_dout;
        end else begin
            k_buf_0_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_94_reg_1739 == 1'd1) & (or_cond_i_i_reg_1798_pp0_iter1_reg == 1'd1) & (icmp_reg_1734 == 1'd0) & (exitcond388_i_reg_1789_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op198_read_state6 == 1'b1)))) begin
        k_buf_0_val_5_we1 = 1'b1;
    end else begin
        k_buf_0_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_1815_pp0_iter14_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter15 == 1'b1))) begin
        p_dst_data_stream_V_blk_n = p_dst_data_stream_V_full_n;
    end else begin
        p_dst_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_1815_pp0_iter14_reg == 1'd1) & (ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_V_write = 1'b1;
    end else begin
        p_dst_data_stream_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_92_reg_1729 == 1'd1) & (icmp_reg_1734 == 1'd1) & (or_cond_i_i_reg_1798_pp0_iter1_reg == 1'd1) & (exitcond388_i_reg_1789_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((or_cond_i_i_reg_1798_pp0_iter1_reg == 1'd1) & (icmp_reg_1734 == 1'd0) & (exitcond388_i_reg_1789_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        p_src_data_stream_V_blk_n = p_src_data_stream_V_empty_n;
    end else begin
        p_src_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op198_read_state6 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op187_read_state6 == 1'b1)))) begin
        p_src_data_stream_V_read = 1'b1;
    end else begin
        p_src_data_stream_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond389_i_fu_467_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1)) & ~((ap_enable_reg_pp0_iter14 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter15 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter14 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter15 == 1'b1)) | ((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ImagLoc_x_fu_809_p2 = ($signed(32'd4294967295) + $signed(t_V_2_reg_369));

assign OP2_V_0_1_fu_423_p1 = $signed(p_kernel_val_0_V_1_read);

assign OP2_V_0_2_fu_427_p1 = $signed(p_kernel_val_0_V_2_read);

assign OP2_V_1_1_fu_435_p1 = $signed(p_kernel_val_1_V_1_read);

assign OP2_V_1_2_fu_439_p1 = $signed(p_kernel_val_1_V_2_read);

assign OP2_V_1_fu_431_p1 = $signed(p_kernel_val_1_V_0_read);

assign OP2_V_2_1_fu_447_p1 = $signed(p_kernel_val_2_V_1_read);

assign OP2_V_2_2_fu_451_p1 = $signed(p_kernel_val_2_V_2_read);

assign OP2_V_2_fu_443_p1 = $signed(p_kernel_val_2_V_0_read);

assign OP2_V_fu_419_p1 = $signed(p_kernel_val_0_V_0_read);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((or_cond_i_reg_1815_pp0_iter14_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op198_read_state6 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op187_read_state6 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((or_cond_i_reg_1815_pp0_iter14_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op198_read_state6 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op187_read_state6 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((or_cond_i_reg_1815_pp0_iter14_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op198_read_state6 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op187_read_state6 == 1'b1)))));
end

assign ap_block_state10_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state19_pp0_stage0_iter15 = ((or_cond_i_reg_1815_pp0_iter14_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0));
end

assign ap_block_state4_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_pp0_stage0_iter2 = (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op198_read_state6 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op187_read_state6 == 1'b1)));
end

assign ap_block_state7_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_532 = ((tmp_94_reg_1739 == 1'd1) & (or_cond_i_i_reg_1798_pp0_iter1_reg == 1'd1) & (icmp_reg_1734 == 1'd0) & (exitcond388_i_reg_1789_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_condition_538 = ((tmp_342_1_reg_1743 == 1'd1) & (or_cond_i_i_reg_1798_pp0_iter1_reg == 1'd1) & (icmp_reg_1734 == 1'd0) & (exitcond388_i_reg_1789_pp0_iter1_reg == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op187_read_state6 = ((or_cond_i_i_reg_1798_pp0_iter1_reg == 1'd1) & (icmp_reg_1734 == 1'd0) & (exitcond388_i_reg_1789_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op198_read_state6 = ((tmp_92_reg_1729 == 1'd1) & (icmp_reg_1734 == 1'd1) & (or_cond_i_i_reg_1798_pp0_iter1_reg == 1'd1) & (exitcond388_i_reg_1789_pp0_iter1_reg == 1'd0));
end

assign brmerge_fu_906_p2 = (tmp_298_0_not_reg_1769 | tmp_100_fu_829_p2);

assign col_assign_1_fu_916_p2 = (tmp_87_fu_401_p2 - x_reg_1802);

assign col_buf_0_val_0_0_fu_959_p3 = ((brmerge_reg_1808_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_3_q0 : tmp_106_fu_948_p5);

assign col_buf_0_val_1_0_fu_977_p3 = ((brmerge_reg_1808_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_4_q0 : tmp_107_fu_966_p5);

assign col_buf_0_val_2_0_fu_995_p3 = ((brmerge_reg_1808_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_5_q0 : tmp_108_fu_984_p5);

assign exitcond388_i_fu_782_p2 = ((t_V_2_reg_369 == tmp_s_fu_383_p2) ? 1'b1 : 1'b0);

assign exitcond389_i_fu_467_p2 = ((t_V_reg_358 == tmp_86_fu_389_p2) ? 1'b1 : 1'b0);

assign f_fu_1476_p1 = p_Result_19_fu_1465_p5;

assign grp_fu_1503_p0 = OP2_V_reg_1671;

assign grp_fu_1503_p1 = grp_fu_1503_p10;

assign grp_fu_1503_p10 = src_kernel_win_0_va_5_fu_192;

assign grp_fu_1511_p0 = OP2_V_1_reg_1686;

assign grp_fu_1511_p1 = grp_fu_1511_p10;

assign grp_fu_1511_p10 = src_kernel_win_0_va_3_fu_184;

assign grp_fu_1519_p0 = OP2_V_2_reg_1701;

assign grp_fu_1519_p1 = grp_fu_1519_p10;

assign grp_fu_1519_p10 = src_kernel_win_0_va_1_fu_176;

assign grp_fu_1526_p0 = OP2_V_2_1_reg_1706;

assign grp_fu_1526_p1 = grp_fu_1526_p10;

assign grp_fu_1526_p10 = src_kernel_win_0_va_fu_172;

assign grp_fu_1539_p0 = OP2_V_1_2_reg_1696;

assign grp_fu_1539_p1 = grp_fu_1539_p10;

assign grp_fu_1539_p10 = src_kernel_win_0_va_7_reg_1850_pp0_iter4_reg;

assign i_V_fu_472_p2 = (t_V_reg_358 + 32'd1);

assign icmp1_fu_803_p2 = ((tmp_122_fu_793_p4 != 31'd0) ? 1'b1 : 1'b0);

assign icmp2_fu_1323_p2 = ((tmp_131_fu_1313_p4 == 26'd0) ? 1'b1 : 1'b0);

assign icmp_fu_493_p2 = ((tmp_102_fu_483_p4 != 31'd0) ? 1'b1 : 1'b0);

assign j_V_fu_787_p2 = (t_V_2_reg_369 + 32'd1);

assign k_buf_0_val_3_address0 = tmp_105_fu_920_p1;

assign k_buf_0_val_4_address0 = tmp_105_fu_920_p1;

assign k_buf_0_val_5_address0 = tmp_105_fu_920_p1;

assign msb_idx_1_fu_1305_p3 = ((tmp_130_fu_1297_p3[0:0] === 1'b1) ? 31'd0 : tmp_129_fu_1293_p1);

assign msb_idx_fu_1288_p2 = (32'd27 - num_zeros_reg_1936);


always @ (p_Result_18_fu_1272_p3) begin
    if (p_Result_18_fu_1272_p3[0] == 1'b1) begin
        num_zeros_fu_1280_p3 = 32'd0;
    end else if (p_Result_18_fu_1272_p3[1] == 1'b1) begin
        num_zeros_fu_1280_p3 = 32'd1;
    end else if (p_Result_18_fu_1272_p3[2] == 1'b1) begin
        num_zeros_fu_1280_p3 = 32'd2;
    end else if (p_Result_18_fu_1272_p3[3] == 1'b1) begin
        num_zeros_fu_1280_p3 = 32'd3;
    end else if (p_Result_18_fu_1272_p3[4] == 1'b1) begin
        num_zeros_fu_1280_p3 = 32'd4;
    end else if (p_Result_18_fu_1272_p3[5] == 1'b1) begin
        num_zeros_fu_1280_p3 = 32'd5;
    end else if (p_Result_18_fu_1272_p3[6] == 1'b1) begin
        num_zeros_fu_1280_p3 = 32'd6;
    end else if (p_Result_18_fu_1272_p3[7] == 1'b1) begin
        num_zeros_fu_1280_p3 = 32'd7;
    end else if (p_Result_18_fu_1272_p3[8] == 1'b1) begin
        num_zeros_fu_1280_p3 = 32'd8;
    end else if (p_Result_18_fu_1272_p3[9] == 1'b1) begin
        num_zeros_fu_1280_p3 = 32'd9;
    end else if (p_Result_18_fu_1272_p3[10] == 1'b1) begin
        num_zeros_fu_1280_p3 = 32'd10;
    end else if (p_Result_18_fu_1272_p3[11] == 1'b1) begin
        num_zeros_fu_1280_p3 = 32'd11;
    end else if (p_Result_18_fu_1272_p3[12] == 1'b1) begin
        num_zeros_fu_1280_p3 = 32'd12;
    end else if (p_Result_18_fu_1272_p3[13] == 1'b1) begin
        num_zeros_fu_1280_p3 = 32'd13;
    end else if (p_Result_18_fu_1272_p3[14] == 1'b1) begin
        num_zeros_fu_1280_p3 = 32'd14;
    end else if (p_Result_18_fu_1272_p3[15] == 1'b1) begin
        num_zeros_fu_1280_p3 = 32'd15;
    end else if (p_Result_18_fu_1272_p3[16] == 1'b1) begin
        num_zeros_fu_1280_p3 = 32'd16;
    end else if (p_Result_18_fu_1272_p3[17] == 1'b1) begin
        num_zeros_fu_1280_p3 = 32'd17;
    end else if (p_Result_18_fu_1272_p3[18] == 1'b1) begin
        num_zeros_fu_1280_p3 = 32'd18;
    end else if (p_Result_18_fu_1272_p3[19] == 1'b1) begin
        num_zeros_fu_1280_p3 = 32'd19;
    end else if (p_Result_18_fu_1272_p3[20] == 1'b1) begin
        num_zeros_fu_1280_p3 = 32'd20;
    end else if (p_Result_18_fu_1272_p3[21] == 1'b1) begin
        num_zeros_fu_1280_p3 = 32'd21;
    end else if (p_Result_18_fu_1272_p3[22] == 1'b1) begin
        num_zeros_fu_1280_p3 = 32'd22;
    end else if (p_Result_18_fu_1272_p3[23] == 1'b1) begin
        num_zeros_fu_1280_p3 = 32'd23;
    end else if (p_Result_18_fu_1272_p3[24] == 1'b1) begin
        num_zeros_fu_1280_p3 = 32'd24;
    end else if (p_Result_18_fu_1272_p3[25] == 1'b1) begin
        num_zeros_fu_1280_p3 = 32'd25;
    end else if (p_Result_18_fu_1272_p3[26] == 1'b1) begin
        num_zeros_fu_1280_p3 = 32'd26;
    end else if (p_Result_18_fu_1272_p3[27] == 1'b1) begin
        num_zeros_fu_1280_p3 = 32'd27;
    end else if (p_Result_18_fu_1272_p3[28] == 1'b1) begin
        num_zeros_fu_1280_p3 = 32'd28;
    end else if (p_Result_18_fu_1272_p3[29] == 1'b1) begin
        num_zeros_fu_1280_p3 = 32'd29;
    end else if (p_Result_18_fu_1272_p3[30] == 1'b1) begin
        num_zeros_fu_1280_p3 = 32'd30;
    end else if (p_Result_18_fu_1272_p3[31] == 1'b1) begin
        num_zeros_fu_1280_p3 = 32'd31;
    end else begin
        num_zeros_fu_1280_p3 = 32'd32;
    end
end

assign or_cond_i424_i_1_fu_604_p2 = (tmp_368_1_fu_599_p2 & rev1_fu_593_p2);

assign or_cond_i424_i_2_fu_667_p2 = (tmp_368_2_fu_662_p2 & rev2_fu_656_p2);

assign or_cond_i424_i_fu_541_p2 = (tmp_97_fu_536_p2 & rev_fu_530_p2);

assign or_cond_i_fu_911_p2 = (icmp_reg_1734 & icmp1_fu_803_p2);

assign or_cond_i_i_fu_834_p2 = (tmp_100_fu_829_p2 & rev3_fu_823_p2);

assign p_Repl2_10_trunc_i_fu_1452_p2 = (tmp27_cast_cast_fu_1445_p3 + tmp_143_fu_1442_p1);

integer ap_tvar_int_0;

always @ (p_Val2_i_i_cast_fu_1258_p1) begin
    for (ap_tvar_int_0 = 28 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 27 - 0) begin
            p_Result_17_fu_1262_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_17_fu_1262_p4[ap_tvar_int_0] = p_Val2_i_i_cast_fu_1258_p1[27 - ap_tvar_int_0];
        end
    end
end

assign p_Result_18_fu_1272_p3 = {{4'd15}, {p_Result_17_fu_1262_p4}};

assign p_Result_19_fu_1465_p5 = {{tmp_70_i_i_fu_1458_p3}, {tmp32_V_6_reg_1977[22:0]}};

assign p_Result_i_i_fu_1426_p4 = {{tmp32_V_6_fu_1422_p1[30:23]}};

assign p_Result_s_fu_1403_p3 = {{26'd0}, {tmp_141_fu_1399_p1}};

assign p_Val2_68_fu_1252_p3 = ((is_neg_reg_1914[0:0] === 1'b1) ? tmp_i_i_cast_fu_1247_p2 : p_Val2_78_2_2_cast_reg_1908);

assign p_Val2_78_0_1_cast_fu_1142_p1 = grp_fu_1503_p3;

assign p_Val2_78_1_fu_1155_p2 = ($signed(tmp21_cast_fu_1152_p1) + $signed(p_Val2_78_0_1_cast_fu_1142_p1));

assign p_Val2_78_2_1_cast_fu_1212_p1 = p_Val2_78_2_1_fu_1207_p2;

assign p_Val2_78_2_1_fu_1207_p2 = ($signed(tmp25_cast_fu_1204_p1) + $signed(grp_fu_1539_p3));

assign p_Val2_78_2_2_cast_fu_1228_p2 = ($signed(p_Val2_78_2_1_fu_1207_p2) + $signed(tmp_112_fu_1219_p1));

assign p_Val2_i_i_cast_fu_1258_p1 = p_Val2_68_fu_1252_p3;

assign p_Val2_s_fu_1222_p2 = ($signed(p_Val2_78_2_1_cast_fu_1212_p1) + $signed(tmp_386_2_2_fu_1216_p1));

assign p_assign_1_fu_848_p2 = (32'd1 - t_V_2_reg_369);

assign p_assign_2_fu_867_p2 = (tmp_91_fu_461_p2 - p_p2_i_i_fu_854_p3);

assign p_assign_3_fu_872_p3 = ((or_cond_i_i_fu_834_p2[0:0] === 1'b1) ? ImagLoc_x_fu_809_p2 : p_assign_2_fu_867_p2);

assign p_assign_6_1_fu_579_p2 = ($signed(32'd4294967294) + $signed(t_V_reg_358));

assign p_assign_6_2_fu_642_p2 = ($signed(32'd4294967293) + $signed(t_V_reg_358));

assign p_assign_7_1_fu_618_p2 = (32'd2 - t_V_reg_358);

assign p_assign_7_2_fu_681_p2 = (32'd3 - t_V_reg_358);

assign p_assign_7_fu_555_p2 = (32'd1 - t_V_reg_358);

assign p_assign_8_1_fu_637_p2 = (tmp_89_fu_413_p2 - p_p2_i425_i_1_fu_624_p3);

assign p_assign_8_2_fu_700_p2 = (tmp_89_fu_413_p2 - p_p2_i425_i_2_fu_687_p3);

assign p_assign_8_fu_574_p2 = (tmp_89_fu_413_p2 - p_p2_i425_i_fu_561_p3);

assign p_dst_data_stream_V_din = ((tmp_i_i_reg_1920_pp0_iter14_reg[0:0] === 1'b1) ? 32'd0 : f_fu_1476_p1);

assign p_neg393_i_fu_395_p2 = ($signed(32'd4294967295) + $signed(p_src_rows_V_read));

assign p_p2_i425_i_1_fu_624_p3 = ((tmp_116_fu_610_p3[0:0] === 1'b1) ? p_assign_7_1_fu_618_p2 : p_assign_6_1_fu_579_p2);

assign p_p2_i425_i_1_p_assig_fu_721_p3 = ((tmp_378_1_fu_632_p2[0:0] === 1'b1) ? p_p2_i425_i_1_fu_624_p3 : p_assign_8_1_fu_637_p2);

assign p_p2_i425_i_2_fu_687_p3 = ((tmp_118_fu_673_p3[0:0] === 1'b1) ? p_assign_7_2_fu_681_p2 : p_assign_6_2_fu_642_p2);

assign p_p2_i425_i_2_p_assig_fu_737_p3 = ((tmp_378_2_fu_695_p2[0:0] === 1'b1) ? p_p2_i425_i_2_fu_687_p3 : p_assign_8_2_fu_700_p2);

assign p_p2_i425_i_fu_561_p3 = ((tmp_114_fu_547_p3[0:0] === 1'b1) ? p_assign_7_fu_555_p2 : tmp_96_fu_516_p2);

assign p_p2_i425_i_p_assign_8_fu_705_p3 = ((tmp_98_fu_569_p2[0:0] === 1'b1) ? p_p2_i425_i_fu_561_p3 : p_assign_8_fu_574_p2);

assign p_p2_i_i_fu_854_p3 = ((tmp_124_fu_840_p3[0:0] === 1'b1) ? p_assign_1_fu_848_p2 : ImagLoc_x_fu_809_p2);

assign r_V_3_0_1_fu_1488_p0 = OP2_V_0_1_reg_1676;

assign r_V_3_0_1_fu_1488_p1 = r_V_3_0_1_fu_1488_p10;

assign r_V_3_0_1_fu_1488_p10 = src_kernel_win_0_va_4_fu_188;

assign r_V_3_0_2_fu_1493_p0 = OP2_V_0_2_reg_1681;

assign r_V_3_0_2_fu_1493_p1 = r_V_3_0_2_fu_1493_p10;

assign r_V_3_0_2_fu_1493_p10 = src_kernel_win_0_va_8_reg_1856;

assign r_V_3_1_1_fu_1498_p0 = OP2_V_1_1_reg_1691;

assign r_V_3_1_1_fu_1498_p1 = r_V_3_1_1_fu_1498_p10;

assign r_V_3_1_1_fu_1498_p10 = src_kernel_win_0_va_2_fu_180;

assign r_V_3_2_2_fu_1534_p0 = OP2_V_2_2_reg_1711;

assign r_V_3_2_2_fu_1534_p1 = r_V_3_2_2_fu_1534_p10;

assign r_V_3_2_2_fu_1534_p10 = src_kernel_win_0_va_6_reg_1844_pp0_iter3_reg;

assign rev1_fu_593_p2 = (tmp_115_fu_585_p3 ^ 1'd1);

assign rev2_fu_656_p2 = (tmp_117_fu_648_p3 ^ 1'd1);

assign rev3_fu_823_p2 = (tmp_123_fu_815_p3 ^ 1'd1);

assign rev_fu_530_p2 = (tmp_104_fu_522_p3 ^ 1'd1);

assign row_assign_8_1_fu_766_p2 = (p_neg393_i_fu_395_p2 - y_1_1_reg_1759);

assign row_assign_8_2_fu_774_p2 = (p_neg393_i_fu_395_p2 - y_1_2_reg_1764);

assign row_assign_8_fu_758_p2 = (p_neg393_i_fu_395_p2 - y_1_reg_1754);

assign sel_tmp7_fu_886_p2 = (tmp_123_fu_815_p3 | tmp_103_not_fu_880_p2);

assign sel_tmp8_fu_892_p2 = (tmp_103_fu_862_p2 & sel_tmp7_fu_886_p2);

assign src_kernel_win_0_va_6_fu_1049_p3 = ((tmp_95_reg_1747[0:0] === 1'b1) ? tmp_109_fu_1038_p5 : col_buf_0_val_0_0_fu_959_p3);

assign src_kernel_win_0_va_7_fu_1067_p3 = ((tmp_95_reg_1747[0:0] === 1'b1) ? tmp_110_fu_1056_p5 : col_buf_0_val_1_0_fu_977_p3);

assign src_kernel_win_0_va_8_fu_1085_p3 = ((tmp_95_reg_1747[0:0] === 1'b1) ? tmp_111_fu_1074_p5 : col_buf_0_val_2_0_fu_995_p3);

assign tmp21_cast_fu_1152_p1 = grp_fu_1511_p3;

assign tmp25_cast_fu_1204_p1 = tmp25_reg_1892;

assign tmp27_cast_cast_fu_1445_p3 = ((tmp_139_i_i_reg_1982[0:0] === 1'b1) ? 8'd114 : 8'd113);

assign tmp32_V_1_fu_1363_p2 = tmp32_V_fu_1351_p1 << tmp_137_i_i_cast_fu_1359_p1;

assign tmp32_V_2_fu_1411_p1 = p_Result_s_fu_1403_p3;

assign tmp32_V_3_fu_1415_p3 = ((icmp2_reg_1951[0:0] === 1'b1) ? tmp32_V_1_fu_1363_p2 : tmp32_V_2_fu_1411_p1);

assign tmp32_V_6_fu_1422_p1 = grp_fu_380_p1;

assign tmp32_V_fu_1351_p1 = p_Val2_68_reg_1925_pp0_iter7_reg;

assign tmp_100_fu_829_p2 = (($signed(ImagLoc_x_fu_809_p2) < $signed(p_src_cols_V_read)) ? 1'b1 : 1'b0);

assign tmp_101_fu_455_p2 = p_src_cols_V_read << 32'd1;

assign tmp_102_fu_483_p4 = {{t_V_reg_358[31:1]}};

assign tmp_103_fu_862_p2 = (($signed(p_p2_i_i_fu_854_p3) < $signed(p_src_cols_V_read)) ? 1'b1 : 1'b0);

assign tmp_103_not_fu_880_p2 = (tmp_100_fu_829_p2 ^ 1'd1);

assign tmp_104_fu_522_p3 = tmp_96_fu_516_p2[32'd31];

assign tmp_105_fu_920_p1 = x_reg_1802;

assign tmp_112_fu_1219_p1 = r_V_3_2_2_reg_1897;

assign tmp_114_fu_547_p3 = tmp_96_fu_516_p2[32'd31];

assign tmp_115_fu_585_p3 = p_assign_6_1_fu_579_p2[32'd31];

assign tmp_116_fu_610_p3 = p_assign_6_1_fu_579_p2[32'd31];

assign tmp_117_fu_648_p3 = p_assign_6_2_fu_642_p2[32'd31];

assign tmp_118_fu_673_p3 = p_assign_6_2_fu_642_p2[32'd31];

assign tmp_119_fu_762_p1 = row_assign_8_fu_758_p2[1:0];

assign tmp_120_fu_770_p1 = row_assign_8_1_fu_766_p2[1:0];

assign tmp_121_fu_778_p1 = row_assign_8_2_fu_774_p2[1:0];

assign tmp_122_fu_793_p4 = {{t_V_2_reg_369[31:1]}};

assign tmp_123_fu_815_p3 = ImagLoc_x_fu_809_p2[32'd31];

assign tmp_124_fu_840_p3 = ImagLoc_x_fu_809_p2[32'd31];

assign tmp_125_fu_926_p1 = col_assign_1_fu_916_p2[1:0];

assign tmp_129_fu_1293_p1 = msb_idx_fu_1288_p2[30:0];

assign tmp_130_fu_1297_p3 = msb_idx_fu_1288_p2[32'd31];

assign tmp_131_fu_1313_p4 = {{msb_idx_1_fu_1305_p3[30:5]}};

assign tmp_132_fu_1329_p1 = msb_idx_1_fu_1305_p3[4:0];

assign tmp_133_fu_1333_p2 = ((msb_idx_1_fu_1305_p3 < 31'd31) ? 1'b1 : 1'b0);

assign tmp_134_fu_1339_p2 = (5'd1 + tmp_132_fu_1329_p1);

integer ap_tvar_int_1;

always @ (p_Val2_i_i_cast_reg_1930_pp0_iter7_reg) begin
    for (ap_tvar_int_1 = 28 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 27 - 0) begin
            tmp_135_fu_1369_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            tmp_135_fu_1369_p4[ap_tvar_int_1] = p_Val2_i_i_cast_reg_1930_pp0_iter7_reg[27 - ap_tvar_int_1];
        end
    end
end

assign tmp_136_fu_1345_p2 = ($signed(5'd26) - $signed(tmp_132_fu_1329_p1));

assign tmp_137_fu_1378_p3 = ((tmp_133_reg_1956[0:0] === 1'b1) ? tmp_135_fu_1369_p4 : p_Val2_i_i_cast_reg_1930_pp0_iter7_reg);

assign tmp_137_i_i_cast_fu_1359_p1 = tmp_137_i_i_fu_1354_p2;

assign tmp_137_i_i_fu_1354_p2 = (31'd31 - msb_idx_1_reg_1946);

assign tmp_138_fu_1384_p3 = ((tmp_133_reg_1956[0:0] === 1'b1) ? tmp_136_reg_1967 : tmp_134_reg_1962);

assign tmp_139_fu_1389_p1 = tmp_138_fu_1384_p3;

assign tmp_139_i_i_fu_1436_p2 = ((p_Result_i_i_fu_1426_p4 != 8'd158) ? 1'b1 : 1'b0);

assign tmp_140_fu_1393_p2 = tmp_137_fu_1378_p3 >> tmp_139_fu_1389_p1;

assign tmp_141_fu_1399_p1 = tmp_140_fu_1393_p2[1:0];

assign tmp_143_fu_1442_p1 = msb_idx_reg_1941_pp0_iter14_reg[7:0];

assign tmp_298_0_not_fu_753_p2 = (tmp_92_reg_1729 ^ 1'd1);

assign tmp_342_1_fu_505_p2 = ((t_V_reg_358 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_368_1_fu_599_p2 = (($signed(p_assign_6_1_fu_579_p2) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_368_2_fu_662_p2 = (($signed(p_assign_6_2_fu_642_p2) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_378_1_fu_632_p2 = (($signed(p_p2_i425_i_1_fu_624_p3) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_378_2_fu_695_p2 = (($signed(p_p2_i425_i_2_fu_687_p3) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_386_2_2_fu_1216_p1 = r_V_3_2_2_reg_1897;

assign tmp_70_i_i_fu_1458_p3 = {{is_neg_reg_1914_pp0_iter14_reg}, {p_Repl2_10_trunc_i_fu_1452_p2}};

assign tmp_86_fu_389_p2 = (32'd2 + p_src_rows_V_read);

assign tmp_87_fu_401_p2 = (32'd3 + p_src_cols_V_read);

assign tmp_89_fu_413_p2 = (32'd2 + tmp_99_fu_407_p2);

assign tmp_91_fu_461_p2 = ($signed(32'd4294967294) + $signed(tmp_101_fu_455_p2));

assign tmp_92_fu_478_p2 = ((t_V_reg_358 < p_src_rows_V_read) ? 1'b1 : 1'b0);

assign tmp_94_fu_499_p2 = ((t_V_reg_358 == 32'd1) ? 1'b1 : 1'b0);

assign tmp_95_fu_511_p2 = ((t_V_reg_358 > p_src_rows_V_read) ? 1'b1 : 1'b0);

assign tmp_96_fu_516_p2 = ($signed(32'd4294967295) + $signed(t_V_reg_358));

assign tmp_97_fu_536_p2 = (($signed(tmp_96_fu_516_p2) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_98_fu_569_p2 = (($signed(p_p2_i425_i_fu_561_p3) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_99_fu_407_p2 = p_src_rows_V_read << 32'd1;

assign tmp_i_i_cast_fu_1247_p2 = (27'd0 - p_Val2_78_2_2_cast_reg_1908);

assign tmp_i_i_fu_1242_p2 = ((p_Val2_s_reg_1903 == 28'd0) ? 1'b1 : 1'b0);

assign tmp_s_fu_383_p2 = (32'd2 + p_src_cols_V_read);

assign x_fu_898_p3 = ((sel_tmp8_fu_892_p2[0:0] === 1'b1) ? p_p2_i_i_fu_854_p3 : p_assign_3_fu_872_p3);

assign y_1_1_fu_729_p3 = ((or_cond_i424_i_1_fu_604_p2[0:0] === 1'b1) ? p_assign_6_1_fu_579_p2 : p_p2_i425_i_1_p_assig_fu_721_p3);

assign y_1_2_fu_745_p3 = ((or_cond_i424_i_2_fu_667_p2[0:0] === 1'b1) ? p_assign_6_2_fu_642_p2 : p_p2_i425_i_2_p_assig_fu_737_p3);

assign y_1_fu_713_p3 = ((or_cond_i424_i_fu_541_p2[0:0] === 1'b1) ? tmp_96_fu_516_p2 : p_p2_i425_i_p_assign_8_fu_705_p3);

always @ (posedge ap_clk) begin
    p_Val2_i_i_cast_reg_1930[27] <= 1'b0;
    p_Val2_i_i_cast_reg_1930_pp0_iter7_reg[27] <= 1'b0;
end

endmodule //Filter2D
