// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fpag_gaus,hls_ip_2018_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=11.187125,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=33,HLS_SYN_DSP=97,HLS_SYN_FF=18596,HLS_SYN_LUT=24981}" *)

module fpag_gaus (
        video_in_TDATA,
        video_in_TKEEP,
        video_in_TSTRB,
        video_in_TUSER,
        video_in_TLAST,
        video_in_TID,
        video_in_TDEST,
        video_out_TDATA,
        video_out_TKEEP,
        video_out_TSTRB,
        video_out_TUSER,
        video_out_TLAST,
        video_out_TID,
        video_out_TDEST,
        rows,
        cols,
        sigma,
        ap_clk,
        ap_rst_n,
        video_in_TVALID,
        video_in_TREADY,
        ap_start,
        video_out_TVALID,
        video_out_TREADY,
        ap_done,
        ap_ready,
        ap_idle
);


input  [7:0] video_in_TDATA;
input  [0:0] video_in_TKEEP;
input  [0:0] video_in_TSTRB;
input  [0:0] video_in_TUSER;
input  [0:0] video_in_TLAST;
input  [0:0] video_in_TID;
input  [0:0] video_in_TDEST;
output  [31:0] video_out_TDATA;
output  [3:0] video_out_TKEEP;
output  [3:0] video_out_TSTRB;
output  [0:0] video_out_TUSER;
output  [0:0] video_out_TLAST;
output  [0:0] video_out_TID;
output  [0:0] video_out_TDEST;
input  [31:0] rows;
input  [31:0] cols;
input  [31:0] sigma;
input   ap_clk;
input   ap_rst_n;
input   video_in_TVALID;
output   video_in_TREADY;
input   ap_start;
output   video_out_TVALID;
input   video_out_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;

reg    ap_rst_n_inv;
wire    AXIvideo2Mat_U0_ap_start;
wire    AXIvideo2Mat_U0_ap_done;
wire    AXIvideo2Mat_U0_ap_continue;
wire    AXIvideo2Mat_U0_ap_idle;
wire    AXIvideo2Mat_U0_ap_ready;
wire    AXIvideo2Mat_U0_video_in_TREADY;
wire   [7:0] AXIvideo2Mat_U0_img_data_stream_V_din;
wire    AXIvideo2Mat_U0_img_data_stream_V_write;
wire    GaussianBlur_U0_ap_start;
wire    GaussianBlur_U0_ap_done;
wire    GaussianBlur_U0_ap_continue;
wire    GaussianBlur_U0_ap_idle;
wire    GaussianBlur_U0_ap_ready;
wire    GaussianBlur_U0_p_src_data_stream_V_read;
wire   [31:0] GaussianBlur_U0_p_dst_data_stream_V_din;
wire    GaussianBlur_U0_p_dst_data_stream_V_write;
wire    Mat2AXIvideo_U0_ap_start;
wire    Mat2AXIvideo_U0_ap_done;
wire    Mat2AXIvideo_U0_ap_continue;
wire    Mat2AXIvideo_U0_ap_idle;
wire    Mat2AXIvideo_U0_ap_ready;
wire    Mat2AXIvideo_U0_img_data_stream_V_read;
wire   [31:0] Mat2AXIvideo_U0_video_out_TDATA;
wire    Mat2AXIvideo_U0_video_out_TVALID;
wire   [3:0] Mat2AXIvideo_U0_video_out_TKEEP;
wire   [3:0] Mat2AXIvideo_U0_video_out_TSTRB;
wire   [0:0] Mat2AXIvideo_U0_video_out_TUSER;
wire   [0:0] Mat2AXIvideo_U0_video_out_TLAST;
wire   [0:0] Mat2AXIvideo_U0_video_out_TID;
wire   [0:0] Mat2AXIvideo_U0_video_out_TDEST;
wire    ap_sync_continue;
wire    srcImg_data_stream_0_full_n;
wire   [7:0] srcImg_data_stream_0_dout;
wire    srcImg_data_stream_0_empty_n;
wire    dstImg_data_stream_0_full_n;
wire   [31:0] dstImg_data_stream_0_dout;
wire    dstImg_data_stream_0_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire    AXIvideo2Mat_U0_start_full_n;
wire    AXIvideo2Mat_U0_start_write;
wire    GaussianBlur_U0_start_full_n;
wire    GaussianBlur_U0_start_write;
wire    Mat2AXIvideo_U0_start_full_n;
wire    Mat2AXIvideo_U0_start_write;

AXIvideo2Mat AXIvideo2Mat_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(AXIvideo2Mat_U0_ap_start),
    .ap_done(AXIvideo2Mat_U0_ap_done),
    .ap_continue(AXIvideo2Mat_U0_ap_continue),
    .ap_idle(AXIvideo2Mat_U0_ap_idle),
    .ap_ready(AXIvideo2Mat_U0_ap_ready),
    .video_in_TDATA(video_in_TDATA),
    .video_in_TVALID(video_in_TVALID),
    .video_in_TREADY(AXIvideo2Mat_U0_video_in_TREADY),
    .video_in_TKEEP(video_in_TKEEP),
    .video_in_TSTRB(video_in_TSTRB),
    .video_in_TUSER(video_in_TUSER),
    .video_in_TLAST(video_in_TLAST),
    .video_in_TID(video_in_TID),
    .video_in_TDEST(video_in_TDEST),
    .img_rows_V(rows),
    .img_cols_V(cols),
    .img_data_stream_V_din(AXIvideo2Mat_U0_img_data_stream_V_din),
    .img_data_stream_V_full_n(srcImg_data_stream_0_full_n),
    .img_data_stream_V_write(AXIvideo2Mat_U0_img_data_stream_V_write)
);

GaussianBlur GaussianBlur_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(GaussianBlur_U0_ap_start),
    .ap_done(GaussianBlur_U0_ap_done),
    .ap_continue(GaussianBlur_U0_ap_continue),
    .ap_idle(GaussianBlur_U0_ap_idle),
    .ap_ready(GaussianBlur_U0_ap_ready),
    .p_src_rows_V(rows),
    .p_src_cols_V(cols),
    .p_src_data_stream_V_dout(srcImg_data_stream_0_dout),
    .p_src_data_stream_V_empty_n(srcImg_data_stream_0_empty_n),
    .p_src_data_stream_V_read(GaussianBlur_U0_p_src_data_stream_V_read),
    .p_dst_data_stream_V_din(GaussianBlur_U0_p_dst_data_stream_V_din),
    .p_dst_data_stream_V_full_n(dstImg_data_stream_0_full_n),
    .p_dst_data_stream_V_write(GaussianBlur_U0_p_dst_data_stream_V_write),
    .sigma(sigma)
);

Mat2AXIvideo Mat2AXIvideo_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Mat2AXIvideo_U0_ap_start),
    .ap_done(Mat2AXIvideo_U0_ap_done),
    .ap_continue(Mat2AXIvideo_U0_ap_continue),
    .ap_idle(Mat2AXIvideo_U0_ap_idle),
    .ap_ready(Mat2AXIvideo_U0_ap_ready),
    .img_rows_V(rows),
    .img_cols_V(cols),
    .img_data_stream_V_dout(dstImg_data_stream_0_dout),
    .img_data_stream_V_empty_n(dstImg_data_stream_0_empty_n),
    .img_data_stream_V_read(Mat2AXIvideo_U0_img_data_stream_V_read),
    .video_out_TDATA(Mat2AXIvideo_U0_video_out_TDATA),
    .video_out_TVALID(Mat2AXIvideo_U0_video_out_TVALID),
    .video_out_TREADY(video_out_TREADY),
    .video_out_TKEEP(Mat2AXIvideo_U0_video_out_TKEEP),
    .video_out_TSTRB(Mat2AXIvideo_U0_video_out_TSTRB),
    .video_out_TUSER(Mat2AXIvideo_U0_video_out_TUSER),
    .video_out_TLAST(Mat2AXIvideo_U0_video_out_TLAST),
    .video_out_TID(Mat2AXIvideo_U0_video_out_TID),
    .video_out_TDEST(Mat2AXIvideo_U0_video_out_TDEST)
);

fifo_w8_d2_A srcImg_data_stream_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_data_stream_V_din),
    .if_full_n(srcImg_data_stream_0_full_n),
    .if_write(AXIvideo2Mat_U0_img_data_stream_V_write),
    .if_dout(srcImg_data_stream_0_dout),
    .if_empty_n(srcImg_data_stream_0_empty_n),
    .if_read(GaussianBlur_U0_p_src_data_stream_V_read)
);

fifo_w32_d2_A dstImg_data_stream_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(GaussianBlur_U0_p_dst_data_stream_V_din),
    .if_full_n(dstImg_data_stream_0_full_n),
    .if_write(GaussianBlur_U0_p_dst_data_stream_V_write),
    .if_dout(dstImg_data_stream_0_dout),
    .if_empty_n(dstImg_data_stream_0_empty_n),
    .if_read(Mat2AXIvideo_U0_img_data_stream_V_read)
);

assign AXIvideo2Mat_U0_ap_continue = 1'b1;

assign AXIvideo2Mat_U0_ap_start = ap_start;

assign AXIvideo2Mat_U0_start_full_n = 1'b1;

assign AXIvideo2Mat_U0_start_write = 1'b0;

assign GaussianBlur_U0_ap_continue = 1'b1;

assign GaussianBlur_U0_ap_start = ap_start;

assign GaussianBlur_U0_start_full_n = 1'b1;

assign GaussianBlur_U0_start_write = 1'b0;

assign Mat2AXIvideo_U0_ap_continue = 1'b1;

assign Mat2AXIvideo_U0_ap_start = ap_start;

assign Mat2AXIvideo_U0_start_full_n = 1'b1;

assign Mat2AXIvideo_U0_start_write = 1'b0;

assign ap_done = Mat2AXIvideo_U0_ap_done;

assign ap_idle = (Mat2AXIvideo_U0_ap_idle & GaussianBlur_U0_ap_idle & AXIvideo2Mat_U0_ap_idle);

assign ap_ready = AXIvideo2Mat_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b1;

assign ap_sync_done = Mat2AXIvideo_U0_ap_done;

assign ap_sync_ready = AXIvideo2Mat_U0_ap_ready;

assign video_in_TREADY = AXIvideo2Mat_U0_video_in_TREADY;

assign video_out_TDATA = Mat2AXIvideo_U0_video_out_TDATA;

assign video_out_TDEST = Mat2AXIvideo_U0_video_out_TDEST;

assign video_out_TID = Mat2AXIvideo_U0_video_out_TID;

assign video_out_TKEEP = Mat2AXIvideo_U0_video_out_TKEEP;

assign video_out_TLAST = Mat2AXIvideo_U0_video_out_TLAST;

assign video_out_TSTRB = Mat2AXIvideo_U0_video_out_TSTRB;

assign video_out_TUSER = Mat2AXIvideo_U0_video_out_TUSER;

assign video_out_TVALID = Mat2AXIvideo_U0_video_out_TVALID;

endmodule //fpag_gaus
