# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/WorkSpace/project/FPGA/prj_ip/prj_ip/prj_ip.srcs/sources_1/ip/fifo_CannyNMS/fifo_CannyNMS.xci
# IP: The module: 'fifo_CannyNMS' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/WorkSpace/project/FPGA/prj_ip/prj_ip/prj_ip.srcs/sources_1/ip/fifo_CannyNMS/fifo_CannyNMS.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_CannyNMS'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/WorkSpace/project/FPGA/prj_ip/prj_ip/prj_ip.srcs/sources_1/ip/fifo_CannyNMS/fifo_CannyNMS_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_CannyNMS'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/WorkSpace/project/FPGA/prj_ip/prj_ip/prj_ip.srcs/sources_1/ip/fifo_CannyNMS/fifo_CannyNMS.xci
# IP: The module: 'fifo_CannyNMS' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/WorkSpace/project/FPGA/prj_ip/prj_ip/prj_ip.srcs/sources_1/ip/fifo_CannyNMS/fifo_CannyNMS.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_CannyNMS'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/WorkSpace/project/FPGA/prj_ip/prj_ip/prj_ip.srcs/sources_1/ip/fifo_CannyNMS/fifo_CannyNMS_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_CannyNMS'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
