# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/WorkSpace/project/FPGA/prj_ip/prj_ip/prj_ip.srcs/sources_1/bd/sift/ip/sift_maxtri3x3_shift_0_1/sift_maxtri3x3_shift_0_1.xci
# IP: The module: 'sift_maxtri3x3_shift_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/WorkSpace/project/FPGA/prj_ip/prj_ip/prj_ip.srcs/sources_1/bd/sift/ip/fifo_maxtrix3x3/fifo_maxtrix3x3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_maxtrix3x3 || ORIG_REF_NAME==fifo_maxtrix3x3} -quiet] -quiet

# XDC: e:/WorkSpace/project/FPGA/prj_ip/prj_ip/prj_ip.srcs/sources_1/bd/sift/ip/fifo_maxtrix3x3/fifo_maxtrix3x3.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_maxtrix3x3 || ORIG_REF_NAME==fifo_maxtrix3x3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: E:/WorkSpace/project/FPGA/prj_ip/prj_ip/prj_ip.srcs/sources_1/bd/sift/ip/sift_maxtri3x3_shift_0_1/sift_maxtri3x3_shift_0_1.xci
# IP: The module: 'sift_maxtri3x3_shift_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/WorkSpace/project/FPGA/prj_ip/prj_ip/prj_ip.srcs/sources_1/bd/sift/ip/fifo_maxtrix3x3/fifo_maxtrix3x3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_maxtrix3x3 || ORIG_REF_NAME==fifo_maxtrix3x3} -quiet] -quiet

# XDC: e:/WorkSpace/project/FPGA/prj_ip/prj_ip/prj_ip.srcs/sources_1/bd/sift/ip/fifo_maxtrix3x3/fifo_maxtrix3x3.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_maxtrix3x3 || ORIG_REF_NAME==fifo_maxtrix3x3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
